name: Plugin Cars
main: ThisMadCat\Car

api: 3.0.0
version: 1.14.0
author: ThisMadCat
site: vk.com/kivanov20040
commands:
 cars:
  default: op
 car:
  default: true
 fuel:
  default: true
